version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: cloudcode
      POSTGRES_USER: cloudcode
      POSTGRES_PASSWORD: Arjuna94944@
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    user: "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: s.krishnarjuna@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Arjun02554206@
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
